GamePortal/GamePortal.Web/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using GamePortal.Common;
using GamePortal.Domain.Contracts;
using GamePortal.Domain.Contracts.Services;
using GamePortal.Domain.Enums;
using GamePortal.Domain.Models.DTO.ResponseModels;

namespace GamePortal.Web.Controllers
{
    public class GameController : BaseSiteController
    {
        public GameController(IServiceHost serviceHost) : base(serviceHost)
        {
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetPaginated(int page = 1, int pageSize = 20, string nameFilter = "",
            List<Guid> selectedGenres = null, List<Guid> selectedTags = null)
        {
            var service = ServiceHost.GetService<IGameService>();
            var result = service.GetGamesPagination(page, pageSize, nameFilter, selectedGenres, selectedTags);
            return new JsonResult
            {
                Data = result,
                MaxJsonLength = int.MaxValue
            };
        }

        [Authorize(Roles = RoleNames.Administrator + "," + RoleNames.Manager)]
        [HttpGet]
        public ActionResult Create()
        {
            return View(new GameResponseModel());
        }

        [Authorize(Roles = RoleNames.Administrator + "," + RoleNames.Manager)]
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(GameResponseModel model, HttpPostedFileBase file)
        {
            var service = ServiceHost.GetService<IGameService>();
            if (file == null || file.ContentLength == 0)
            {
                return Json(new
                {
                    success = false,
                    message = "Выберите картинку для заставки."
                });
            }
            if (!FileHelper.IsImage(file.ContentType))
            {
                return Json(new
                {
                    success = false,
                    message = "Неверный формат файла. Требуется изображение."
                });
            }
            var result = service.AddGame(model, file, CurrentUserId);
            return Json(new
            {
                success = result.IsOk,
                message = result.Message
            });
        }

        public ActionResult Game(Guid gameId)
        {
            var service = ServiceHost.GetService<IGameService>();
            var model = service.GetGameWithUser(gameId, CurrentUser);
            return View(model);
        }

        [Authorize(Roles = RoleNames.Administrator + "," + RoleNames.Manager)]
        [HttpGet]
        public ActionResult Edit(Guid gameId)
        {
            var service = ServiceHost.GetService<IGameService>();
            var model = service.GetGame(gameId);
            return View(model);
        }

        [Authorize(Roles = RoleNames.Administrator + "," + RoleNames.Manager)]
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(GameResponseModel model, HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0 && !FileHelper.IsImage(file.ContentType))
            {
                return Json(new
                {
                    success = false,
                    message = "Неверный формат файла. Требуется изображение."
                });
            }
            var service = ServiceHost.GetService<IGameService>();
            var result = service.UpdateGame(model, file);
            return Json(new
            {
                success = result.IsOk,
                message = result.Message
            });
        }

        [Authorize(Roles = RoleNames.Administrator + "," + RoleNames.Manager)]
        public ActionResult Delete(Guid gameId)
        {
            var service = ServiceHost.GetService<IGameService>();
            var result = service.DeleteGame(gameId);
            return Json(new
            {
                success = result.IsOk,
                message = result.Message
            }, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = RoleNames.Administrator + "," + RoleNames.Manager)]
        [HttpPost]
        public JsonResult UploadFile(HttpPostedFileBase file)
        {
            if (file.ContentLength == 0)
                return Json(new
                {
                    error = "Выберите файл."
                }, JsonRequestBehavior.AllowGet);
            try
            {
                var result = ServiceHost.GetService<IFileService>().UploadGameFiles(file);
                return Json(new
                {
                    success = true,
                    data = result
                });
            }
            catch (Exception e)
            {
                return Json(new
                {
                    error = e
                }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult AddComment(string text, Guid gameId, Guid? replyId)
        {
            var service = ServiceHost.GetService<IGameService>();
            var result = service.AddComment(text, gameId, replyId, CurrentUserId);
            return Json(new
            {
                success = result.IsOk,
                message = result.Message
            });
        }

        [HttpPost]
        public JsonResult Vote(Guid gameId, ScoreType score)
        {
            var service = ServiceHost.GetService<IGameService>();
            var result = service.VoteGame(gameId, score, CurrentUserId);
            return Json(new
            {
                success = result.IsOk,
                message = result.Message
            });
        }

        [HttpPost]
        public JsonResult VoteComment(Guid commentId, ScoreType score)
        {
            var service = ServiceHost.GetService<IGameService>();
            var result = service.VoteComment(commentId, score, CurrentUserId);
            return Json(new
            {
                success = result.IsOk,
                message = result.Message
            });
        }

        public ActionResult Image(Guid fileId)
        {
            var service = ServiceHost.GetService<IFileService>();
            var path = service.GetGameFilePath(fileId);
            return File(path, FileHelper.GetMymeType(path));
        }
    }
}

GamePortal/GamePortal.Web/Views/Game/Create.cshtml
@model GamePortal.Domain.Models.DTO.ResponseModels.GameResponseModel

@{
    ViewBag.Title = "Добавление игры";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Create", "Game", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <hr />
    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "control-label" })
        <div>
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control text-center", data_bind = "value: $root.model().Name" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.HeaderFile.Url, new { @class = "control-label" })
        <div>
            <input type="file" data-bind="event: { change: $root.OnHeaderFileSelected }" class="btn btn-default" style="display: inline-block;" accept="image/*" />
        </div>
        <div>
            <img id="previewHeaderFile" src="#" alt="Заставка" width="500" style="display: none" />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Description, new { @class = "control-label" })
        <div>
            <textarea id="Description" data-bind="text: $root.model().Description"></textarea>
            <input type="file" id="game-files" class="btn btn-default" style="display: none;" accept="image/*" />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Genres, new { @class = "control-label" })
        <div id="textarea-autocomplete-to-genres">
            <!-- ko foreach: $root.model().Genres -->
            <button data-bind="click: $root.RemoveGenre, text: Name"></button>
            <!-- /ko -->
            <input />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Tags, new { @class = "control-label" })
        <div id="textarea-autocomplete-to-tags">
            <!-- ko foreach: $root.model().Tags -->
            <button data-bind="click: $root.RemoveTag, text: Name"></button>
            <!-- /ko -->
            <input />
        </div>
    </div>

    <div class="form-group">
        <div>
            <div class="btn-group">
                <input type="button" class="btn btn-info col-md-6" data-bind="click: $root.Save " value="Сохранить" style="width: 55%">
                <a href='@Url.Action("Index")' class="btn btn-primary">Назад</a>
            </div>
        </div>
    </div>
}

@section Scripts{
    <script src="~/Scripts/viewModels/GameViewModel.js"></script>
    <script src="~/Scripts/models/GameModel.js"></script>
    <script>
        ko.applyBindings(new GameVm(new GameModel()));
    </script>
}

GamePortal/GamePortal.Web/Views/Game/Edit.cshtml
@model GamePortal.Domain.Models.DTO.ResponseModels.GameResponseModel

@{
    ViewBag.Title = $"Редактирование игры \"{Model.Name}\"";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "Game", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <hr />
    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "control-label" })
        <div>
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control text-center", data_bind = "value: $root.model().Name" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.HeaderFile.Url, new { @class = "control-label" })
        <div>
            <input type="file" data-bind="event: { change: $root.OnHeaderFileSelected }" class="btn btn-default" style="display: inline-block;" accept="image/*" />
        </div>
        <div>
            <img id="previewHeaderFile" data-bind="attr: {src: $root.model().HeaderFile.Url}, visible: $root.model().HeaderFile.Url" alt="your image" width="500" />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Description, new { @class = "control-label" })
        <div>
            <textarea id="Description" data-bind="text: $root.model().Description"></textarea>
            <input type="file" id="game-files" class="btn btn-default" style="display: none;" accept="image/*" />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Genres, new { @class = "control-label" })
        <div id="textarea-autocomplete-to-genres">
            <!-- ko foreach: $root.model().Genres -->
            <button data-bind="click: $root.RemoveGenre, text: Name"></button>
            <!-- /ko -->
            <input />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Tags, new { @class = "control-label" })
        <div id="textarea-autocomplete-to-tags">
            <!-- ko foreach: $root.model().Tags -->
            <button data-bind="click: $root.RemoveTag, text: Name"></button>
            <!-- /ko -->
            <input />
        </div>
    </div>

    <div class="form-group">
        <div>
            <div class="btn-group">
                <input type="button" class="btn btn-info col-md-6" data-bind="click: $root.Save " value="Сохранить" style="width: 55%">
                <a href='@Url.Action("Index")' class="btn btn-primary">Назад</a>
            </div>
        </div>
    </div>
}

@section Scripts{
    <script src="~/Scripts/viewModels/GameViewModel.js"></script>
    <script src="~/Scripts/models/GameModel.js"></script>
    <script>
        ko.applyBindings(new GameVm(new GameModel(ko.mapping.fromJS(@Html.Raw(Json.Encode(Model)))), true));
    </script>
}

GamePortal/GamePortal.Web/Views/Game/Game.cshtml
@model GamePortal.Domain.Models.DTO.ViewModels.GameViewModel
@{
    ViewBag.Title = Model.Name;
}

<section id="application-form">
    <section>
        <header>
            <h1>@Model.Name</h1>
            <div>
                <img src="@Model.HeaderFilePath" alt="@Model.Name" width="500" />
                <button data-bind="click: function() { $root.Vote(1) }"><i class="fa-thumbs-up" data-bind="css: $root.isGameLiked"></i><span data-bind="text: $root.model().PositiveVotes"></span></button>
                <button data-bind="click:  function() {  $root.Vote(-1) }"><i class="fa-thumbs-down" data-bind="css: $root.isGameUnliked"></i><span data-bind="text: $root.model().NegativeVotes"></span></button>
            </div>
            <div style="margin: 10px 0;">
                @if (Model.Genres.Count > 0)
                {
                    <span>
                        Жанры:
                        @foreach (var genre in Model.Genres)
                        {
                            <button>
                                @genre.Name
                            </button>
                        }
                    </span>
                }
            </div>
            <div>
                @if (Model.Tags.Count > 0)
                {
                    <span>
                        Тэги:
                        @foreach (var tag in Model.Tags)
                        {
                            <button>
                                @tag.Name
                            </button>
                        }
                    </span>
                }
            </div>
        </header>
        <hr />

        <h2>Описание</h2>
        @Html.Raw(Model.Description)
    </section>
    <hr />
    @if (Model.Comments.Count > 0)
    {
        <section>
            <h2>Комментарии</h2>
            <div data-bind="template: { name: 'formElementNodeTemplate', foreach: $root.model().Comments }"></div>
        </section>
    }
    <section>
        <p>Оставьте свой комментарий</p>
        <div data-bind="if: replyToComment">
            <button data-bind="text: replyName, click: $root.CancelReply"></button>
        </div>
        <input type="text" data-bind="value: commentText" />
        <button class="btn" data-bind="click: $root.SendComment">Отправить</button>
    </section>
    <br />
</section>

@section Scripts{
    <script id="formElementNodeTemplate" type="text/html">
        <ul style="list-style-type: none;">
            <li>
                <div>
                    <span data-bind="text: CreatedByUserName"></span>
                </div>
                <div>
                    <span data-bind="text: Text"></span>
                    <span data-bind="text: CreateDateTime" style="margin-left: 15px;"></span>
                    <button data-bind="click: function() { $root.VoteComment($data, 1) }"><i class="fa-thumbs-up" data-bind="css: { fas: IsLiked(), far: !IsLiked() }"></i><span data-bind="text: PositiveVotes"></span></button>
                    <button data-bind="click: function() { $root.VoteComment($data, -1) }"><i class="fa-thumbs-down" data-bind="css: { fas: IsUnliked(), far: !IsUnliked() }"></i><span data-bind="text: NegativeVotes"></span></button>
                </div>
                <button data-bind="click: $root.ReplyToComment">Ответить</button>
                <br />
                <!-- ko template: { name: 'formElementNodeTemplate', foreach: RepliesToComment() } -->
                <!-- /ko -->
            </li>
        </ul>
    </script>
    <script src="~/Scripts/viewModels/GameViewModel.js"></script>
    <script src="~/Scripts/models/GameModel.js"></script>
    <script>
        ko.applyBindings(new GameVm(new GameModel(ko.mapping.fromJS(@Html.Raw(Json.Encode(Model))))));
    </script>
}

GamePortal/GamePortal.Web/Views/Game/Index.cshtml
@{
    ViewBag.Title = "Игры";
}

<h2>@ViewBag.Title</h2>

<p>
    <div class="btn-group">
        @Html.ActionLink("Добавить игру", "Create", new { }, new { @class = "btn btn-success" })
    </div>
</p>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th colspan="2">
                <input placeholder="Имя" type="text" data-bind="value: nameFilter" class="form-control" />
            </th>
            <th data-bind="foreach: $root.selectedGenres">
                <button data-bind="click: $root.RemoveGenreFromSearch, text: Name"></button>
            </th>
            <th data-bind="foreach: $root.selectedTags">
                <button data-bind="click: $root.RemoveTagFromSearch, text: Name"></button>
            </th>
            <th>
                <button type="submit" class="btn btn-info" style="max-width: none; width: 100%;" data-bind="click: $root.Search(1, true)">
                    <i class="fa fa-search"></i>&nbsp;Поиск
                </button>
            </th>
        </tr>
        <tr>
            <th>Заставка</th>
            <th>Имя</th>
            <th>Жанры</th>
            <th>Тэги</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody data-bind="foreach: $root.gamesList()">
        <tr>
            <td class="col-md-2">
                <img data-bind="attr:{src: HeaderFile.Url, alt: Name}" width="100" />
            </td>
            <td class="col-md-2" data-bind="text: Name"></td>
            <td class="col-md-3" data-bind="foreach: Genres">
                <button data-bind="text: Name, click: $root.AddGenreToSearch"></button>
            </td>
            <td class="col-md-3" data-bind="foreach: Tags">
                <button data-bind="text: Name, click: $root.AddTagToSearch"></button>
            </td>
            <td class="col-md-2">
                <a class="btn btn-default" title="Посмотреть" data-bind="click: function(){$root.OpenGame(Id)}"><i class="far fa-eye"></i></a>
                @{
                    if (User.IsInRole("Admin") || User.IsInRole("Manager"))
                    {
                        <a class="btn btn-default" title="Изменить" data-bind="click: function(){$root.EditGame(Id)}"><i class="fas fa-pencil-alt"></i></a>
                        <a class="btn btn-default" title="Удалить" data-bind="click: function(){$root.DeleteGame(Id)}"><i class="fas fa-trash-alt"></i></a>
                    }
                }
            </td>
        </tr>
    </tbody>
</table>

<div id="divPagination">Страница 1</div>
<div class="row">
    <ul class="col-md-7 col-md-offset-0" id="ulPagination"></ul>
</div>

@section Scripts{
    <script src="~/Scripts/viewModels/GameViewModel.js"></script>
    <script src="~/Scripts/models/GameModel.js"></script>
    <script>
        ko.applyBindings(new GameVm(new GameModel()));
    </script>
}