GamePortal/GamePortal.Web/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using GamePortal.Domain.Contracts;
using GamePortal.Domain.Contracts.Services;
using GamePortal.Domain.Enums;
using GamePortal.Domain.Models.DTO.ResponseModels;

namespace GamePortal.Web.Controllers
{
    public class TagController : BaseSiteController
    {
        public TagController(IServiceHost serviceHost) : base(serviceHost)
        {
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetTagsPaginated(int page = 1, int pageSize = 20, string nameFilter = "", List<Guid> selectedTags = null)
        {
            return Json(new
            {
                Data = ServiceHost.GetService<ITagService>().GetTagsPagination(page, pageSize, nameFilter, selectedTags)
            }, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = RoleNames.Administrator + "," + RoleNames.Manager)]
        [HttpGet]
        public ActionResult Create()
        {
            return View(new TagResponseModel());
        }
        
        [Authorize(Roles = RoleNames.Administrator + "," + RoleNames.Manager)]
        [HttpPost]
        public ActionResult Create(TagResponseModel model)
        {
            if (!ModelState.IsValid) return View(model);
            var result = ServiceHost.GetService<ITagService>().AddTag(model);
            if (result.IsOk)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", result.Message);
            return View(model);
        }

        [Authorize(Roles = RoleNames.Administrator + "," + RoleNames.Manager)]
        [HttpGet]
        public ActionResult Edit(Guid tagId)
        {
            var tagService = ServiceHost.GetService<ITagService>();
            var model = tagService.GetTag(tagId);
            return View(model);
        }

        [Authorize(Roles = RoleNames.Administrator + "," + RoleNames.Manager)]
        [HttpPost]
        public ActionResult Edit(TagResponseModel model)
        {
            if (!ModelState.IsValid) return View(model);
            var result = ServiceHost.GetService<ITagService>().UpdateTag(model);
            if (result.IsOk)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", result.Message);
            return View(model);
        }

        [Authorize(Roles = RoleNames.Administrator + "," + RoleNames.Manager)]
        public JsonResult Delete(Guid tagId)
        {
            var result = ServiceHost.GetService<ITagService>().DeleteTag(tagId);
            return Json(new
            {
                Success = result.IsOk,
                result.Message
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

GamePortal/GamePortal.Web/Views/Tag/Create.cshtml
@model GamePortal.Domain.Models.DTO.ResponseModels.TagResponseModel
@{
    ViewBag.Title = "Добавление тэга";
}

@using (Html.BeginForm("Create", "Tag", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4><b>@ViewBag.Title</b></h4>
    <div style="color: red">
        @Html.ValidationSummary()
    </div>
    <hr />
    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "control-label" })
        <div>
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div>
            <div class="btn-group">
                <input type="submit" class="btn btn-success" value="Сохранить">
                <a href='@Url.Action("Index")' class="btn btn-primary">Назад</a>
            </div>
        </div>
    </div>
}

GamePortal/GamePortal.Web/Views/Tag/Edit.cshtml
@model GamePortal.Domain.Models.DTO.ResponseModels.TagResponseModel
@{
    ViewBag.Title = $"Редактирование тэга \"{Model.Name}\"";
}

@using (Html.BeginForm("Edit", "Tag", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4><b>@ViewBag.Title</b></h4>
    @Html.HiddenFor(x => x.Id)
    <div style="color: red">
        @Html.ValidationSummary()
    </div>
    <hr />
    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "control-label" })
        <div>
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div>
            <div class="btn-group">
                <input type="submit" class="btn btn-success" value="Сохранить">
                <a href='@Url.Action("Index")' class="btn btn-primary">Назад</a>
            </div>
        </div>
    </div>
}

GamePortal/GamePortal.Web/Views/Tag/Index.cshtml
@{
    ViewBag.Title = "Тэги";
}

<h2>@ViewBag.Title</h2>

<p>
    <div class="btn-group">
        @Html.ActionLink("Добавить тэг", "Create", new { }, new { @class = "btn btn-success" })
    </div>
</p>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                <input placeholder="Имя" type="text" data-bind="value: nameFilter" class="form-control" />
            </th>
            <th>
                <button type="submit" class="btn btn-info" style="max-width: none; width: 100%;" data-bind="click: $root.Search(1, true)">
                    <i class="fa fa-search"></i>&nbsp;Поиск
                </button>
            </th>
        </tr>
        <tr>
            <th>Имя</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody data-bind="foreach: $root.tagsList()">
        <tr>
            <td class="col-md-3" data-bind="text: Name"></td>
            <td class="col-md-1">
                <a class="btn btn-default" title="Изменить" data-bind="click: function(){$root.EditTag(Id)}"><i class="fa fa-pencil-alt"></i></a>
                <a class="btn btn-default" title="Удалить" data-bind="click: function(){$root.DeleteTag(Id)}"><i class="fa fa-trash-alt"></i></a>
            </td>
        </tr>
    </tbody>
</table>

<div id="divPagination">Страница 1</div>
<div class="row">
    <ul class="col-md-7 col-md-offset-0" id="ulPagination"></ul>
</div>

@section Scripts{
    <script src="~/Scripts/viewModels/TagViewModel.js"></script>
    <script>
        ko.applyBindings(new TagVm());
    </script>
}