GamePortal/GamePortal.Web/Controllers/ClientController.cs
using System;
using System.Web.Mvc;
using GamePortal.Domain.Contracts;
using GamePortal.Domain.Contracts.Services;
using GamePortal.Domain.Enums;
using GamePortal.Domain.Models.DTO.ResponseModels;

namespace GamePortal.Web.Controllers
{
    public class ClientController : BaseSiteController
    {
        public ClientController(IServiceHost serviceHost) : base(serviceHost)
        {
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetClientsPaginated(int page = 1, int pageSize = 20, string nameFilter = "")
        {
            return Json(new
            {
                Data = ServiceHost.GetService<IClientService>().GetClientsPagination(page, pageSize, nameFilter, CurrentUserId)
            }, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = RoleNames.Administrator + "," + RoleNames.Manager)]
        [HttpGet]
        public ActionResult Create()
        {
            return View(new ClientResponseModel());
        }

        [Authorize(Roles = RoleNames.Administrator + "," + RoleNames.Manager)]
        [HttpPost]
        public ActionResult Create(ClientResponseModel model)
        {
            if (!ModelState.IsValid) return View(model);
            var result = ServiceHost.GetService<IClientService>().AddClient(model, CurrentUserId);
            if (result.IsOk)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", result.Message);
            return View(model);
        }

        [Authorize(Roles = RoleNames.Administrator + "," + RoleNames.Manager)]
        [HttpGet]
        public ActionResult Edit(Guid clientId)
        {
            var clientService = ServiceHost.GetService<IClientService>();
            var model = clientService.GetClient(clientId);
            if (model.CreatedById != CurrentUserId)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [Authorize(Roles = RoleNames.Administrator + "," + RoleNames.Manager)]
        [HttpPost]
        public ActionResult Edit(ClientResponseModel model)
        {
            if (!ModelState.IsValid) return View(model);
            if (model.CreatedById != CurrentUserId)
            {
                ModelState.AddModelError("", @"У вас нет прав на редактирование.");
            }
            var result = ServiceHost.GetService<IClientService>().UpdateClient(model);
            if (result.IsOk)
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", result.Message);
            return View(model);
        }

        [Authorize(Roles = RoleNames.Administrator + "," + RoleNames.Manager)]
        public JsonResult Delete(Guid clientId)
        {
            var result = ServiceHost.GetService<IClientService>().DeleteClient(clientId, CurrentUserId);
            return Json(new
            {
                Success = result.IsOk,
                result.Message
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

GamePortal/GamePortal.Web/Views/Client/Create.cshtml
@model GamePortal.Domain.Models.DTO.ResponseModels.ClientResponseModel
@{
    ViewBag.Title = "Добавление клиента";
}

@using (Html.BeginForm("Create", "Client", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4><b>@ViewBag.Title</b></h4>
    <div style="color: red">
        @Html.ValidationSummary()
    </div>
    <hr />
    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "control-label" })
        <div>
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Secret, new { @class = "control-label" })
        <div>
            @Html.TextBoxFor(x => x.Secret, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.WebSiteUrl, new { @class = "control-label" })
        <div>
            @Html.TextBoxFor(x => x.WebSiteUrl, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.RedirectUrl, new { @class = "control-label" })
        <div>
            @Html.TextBoxFor(x => x.RedirectUrl, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div>
            <div class="btn-group">
                <input type="submit" class="btn btn-success" value="Сохранить">
                <a href='@Url.Action("Index")' class="btn btn-primary">Назад</a>
            </div>
        </div>
    </div>
}

GamePortal/GamePortal.Web/Views/Client/Edit.cshtml
@model GamePortal.Domain.Models.DTO.ResponseModels.ClientResponseModel
@{
    ViewBag.Title = $"Редактирование клиента \"{Model.Name}\"";
}

@using (Html.BeginForm("Edit", "Client", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4><b>@ViewBag.Title</b></h4>
    @Html.HiddenFor(x => x.Id)
    @Html.HiddenFor(x => x.CreatedById)
    <div style="color: red">
        @Html.ValidationSummary()
    </div>
    <hr />
    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "control-label" })
        <div>
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Secret, new { @class = "control-label" })
        <div>
            @Html.TextBoxFor(x => x.Secret, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.WebSiteUrl, new { @class = "control-label" })
        <div>
            @Html.TextBoxFor(x => x.WebSiteUrl, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.RedirectUrl, new { @class = "control-label" })
        <div>
            @Html.TextBoxFor(x => x.RedirectUrl, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div>
            <div class="btn-group">
                <input type="submit" class="btn btn-success" value="Сохранить">
                <a href='@Url.Action("Index")' class="btn btn-primary">Назад</a>
            </div>
        </div>
    </div>
}

GamePortal/GamePortal.Web/Views/Client/Index.cshtml
@{
    ViewBag.Title = "Клиенты";
}

<h2>@ViewBag.Title</h2>

<p>
    <div class="btn-group">
        @Html.ActionLink("Добавить клиента", "Create", new { }, new { @class = "btn btn-success" })
    </div>
</p>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th colspan="3">
                <input placeholder="Имя" type="text" data-bind="value: nameFilter" class="form-control" />
            </th>
            <th>
                <button type="submit" class="btn btn-info" style="max-width: none; width: 100%;" data-bind="click: $root.Search(1, true)">
                    <i class="fa fa-search"></i>&nbsp;Поиск
                </button>
            </th>
        </tr>
        <tr>
            <th>Айди</th>
            <th>Имя</th>
            <th>Секрет</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody data-bind="foreach: $root.clientsList()">
        <tr>
            <td class="col-md-3" data-bind="text: Id"></td>
            <td class="col-md-3" data-bind="text: Name"></td>
            <td class="col-md-3" data-bind="text: Secret"></td>
            <td class="col-md-1">
                <a class="btn btn-default" title="Изменить" data-bind="click: function(){$root.EditClient(Id)}"><i class="fa fa-pencil-alt"></i></a>
                <a class="btn btn-default" title="Удалить" data-bind="click: function(){$root.DeleteClient(Id)}"><i class="fa fa-trash-alt"></i></a>
            </td>
        </tr>
    </tbody>
</table>

<div id="divPagination">Страница 1</div>
<div class="row">
    <ul class="col-md-7 col-md-offset-0" id="ulPagination"></ul>
</div>

@section Scripts{
    <script src="~/Scripts/viewModels/ClientViewModel.js"></script>
    <script>
        ko.applyBindings(new ClientVm());
    </script>
}